### ISSUE TITLE
Decause needs to make an Inkscape lecture

### ISSUE THREAD

**Issue by liam-middlebrook** [FOSSRIT/fossbox-tasks#10]
@decause Mentioned during ADVFOSS that he should make an inkscape lecture and add it to. https://github.com/decause/advfoss

**Comment by jflory7** [comment]
This could also be a task for a FOSSBoxer or another professor / instructor.

**Comment by jflory7** [comment]
This could be something @ritjoe could consider for future editions of the course or for the [foss-minor](https://github.com/FOSSRIT/foss-minor) repository (once implemented).

**Comment by jflory7** [comment]
Closing issue. We can revisit this for the minor if needed at a later time.
