### ISSUE TITLE
Monthly, summer FOSShours

### ISSUE THREAD

**Issue by jflory7** [FOSSRIT/fossbox-tasks#15]
In the last week or classes or in FOSShours, @ritjoe suggested the idea of having monthly, two-hour FOSShours in June and July where we can have planned times for the FOSS community at RIT to get together on IRC, check in with each other, see what's new, and other "usual business" that happens at FOSShours.

# Choosing a time

To make syncing up and finding a time that works best easier, I created a [WhenIsGood poll](http://whenisgood.net/rit/foss/fosshours-summer16) that we can use to coordinate times. If you are interested in participating in this, please choose any times that work best for you, generally. It uses a typical Mon-Sun week, so based on your weekly schedule, please select the times that work for you.

If you have any dates that you know you will not be able to participate in, please comment on this issue with the dates.

Additionally, when filling out the poll, make sure you adjust your time zone **before submitting** if you are _not_ in US Eastern.

# Interested people?

I've ~~probably going to send~~ _done_ a blast out to the FOSS Seminar mailing list, but I'll also tag some people who may be interested based on attendees at FOSShours last semester (and maybe a few alumni too).

* @itprofjacobs 
* @schneidy 
* @ritjoe 
* @Serubin 
* @Nolski 
* @brendan-w 
* @msoucy 
* @wilfriedE 
* @abkahrs 
* @Chris-Bitler 
* @ryansb 
* @decause 

I know I probably forgot some names, but it's pretty late and I'm tired. :P 

Hope to see some of you over the summer in channel!

**Comment by Chris-Bitler** [comment]
This might seem like an odd suggestion, but for people that want the actual feel of like talking to people like at the fosshours, perhaps open it up to having people in a google hangouts call or something?

**Comment by abkahrs** [comment]
Voi that is odd and not very FOSSy

-----Original Message-----

**Comment by jflory7** [comment]
@Chris-Bitler I'm not opposed to doing a video call. Although depending on the hours selected, it may be easier for some folks who are on the clock or otherwise occupied to participate in IRC versus a video call. I guess it would depend on the time that is chosen.

**Comment by Chris-Bitler** [comment]
@aidan if you have a more FOSSy way of doing video/audio calls, that could also work.

**Comment by jflory7** [comment]
@Chris-Bitler @abkahrs A FOSS video conferencing suite I've been using a little bit is [Jitsi](https://jitsi.org/). On any remotely recent device and with a decent amount of bandwidth, it works pretty well, although it's under a fair amount of development. But nine times out of ten it works for me if you're in the US. Something we could consider using too to keep things FOSS.

**Comment by abkahrs** [comment]
I agree with the comment by jflory. irc would be better for me since it is not limited to my desktop and it would be odd doing a video call with more than 4 people. Also as requested in original email I put my availability in the survey and here it is again.
Busy M-F 830am to 430pm and Sun 6 to 7 pm

-----Original Message-----

**Comment by ColdSauce** [comment]
I would love to do this! I don't have any specific times since I have no idea how busy I'll be. I also think a Google Hangout would be pretty cool.

**Comment by schneidy** [comment]
I think a Google Hangout is preferential as it can handle the load of more
than 5 people easily. Using it isn't as awkward as most people think when
you have more than 4 people in a room. It just won't be the same as when
we're all together during FOSS hours.

I do recommend thinking about holding this on evenings more than weekends
as it's summer. But that could just be me.

**Comment by Serubin** [comment]
I'm thinking hangouts is a good bet. Weekends are also generally prefered.

**Comment by jflory7** [comment]
As of now, it's looking like M-T-W-F evenings past 8pm works best for the largest number of people (so far). Fridays at 5pm also seems to be a good time. So far, I'm thinking we should be able to pick a time that works for a large number of people, and we could also alternate the two meet-ups to use different times.

For everyone's planning purposes, here is the [current list of times that work](http://whenisgood.net/rit/foss/fosshours-summer16/results/bqhyfq2).

**Comment by jflory7** [comment]
So… I dropped the ball on this one. @jflory7--

Maybe this is something we can revisit in the coming semester, but for now, I think we can discuss this / focus on it in-person or make sure to follow up and act on it next summer. We'll cross that bridge soon.
