### ISSUE TITLE
Organize FOSS Family get-together / dinner

### ISSUE THREAD

**Issue by jflory7** [FOSSRIT/fossbox-tasks#16]
## Current plan (as of 2016-08-22, 22:00)

* **Where**: MAGIC Center, by comfy chairs
* **When**: Tuesday, Aug. 23, 2016, ~6:00pm US EST

And probably leaving for food around 6:30pm.

## What is it?

As discussed earlier in IRC and/or other communication channels, there's a lot of people in the Rochester area for the next few days who will not be here for much longer, whether it's for co-op, careers, or other reasons. To take advantage of this convenient timing, we'd like to get some of the FOSS@RIT folks together for a small get-together and probably dinner too.

This issue can serve as the tracker for organizing final details on this.

## Choosing a time and place

Based on the queries I've made, the most people will be available on **Tuesday, August 23, 2016** some time after 5:00pm. I'd like to propose 6pm as the meeting time.

We could meet in the MAGIC Center, hang out for a bit, and then grab food somewhere (on or off campus, I think we have enough wheels to manage this). I'm open to anywhere personally.

## Attendees

Currently, the people I have confirmed for this are:

* @Serubin 
* @Nolski 
* @brendan-w 
* @wilfriedE 
* @repkam09
* @Awmusic12635 
* @ritjoe 
* @repkam09
* @abkahrs

Of course, this invite is open to any members of FOSS@RIT too. Not sure if @schneidy or @ritjoe would be interested, but the invite definitely extends to them too. :smile: If you see this issue and you're interested in hanging with us on Tuesday, drop a line here so we know to expect you.

If I forgot anything or anyone, hopefully someone can fill the gaps.

**Comment by schneidy** [comment]
Interested, but already booked for that evening :(

**Comment by ritjoe** [comment]
On Sat, Aug 20, 2016 at 10:38:31PM -0700, Justin W. Flory wrote:
> What is it?
> 
> As discussed earlier in IRC and/or other communication channels, there's a lot
> of people in the Rochester area for the next few days who will not be here for
> much longer, whether it's for co-op, careers, or other reasons. To take
> advantage of this convenient timing, we'd like to get some of the FOSS@RIT
> folks together for a small get-together and probably dinner too.
> 
> This issue can serve as the tracker for organizing final details on this.
> 
> Choosing a time and place
> 
> Based on the queries I've made, the most people will be available on Tuesday,
> August 23, 2016 some time after 5:00pm. I'd like to propose 6pm as the meeting
> time.
> 
> We could meet in the MAGIC Center, hang out for a bit, and then grab food
> somewhere (on or off campus, I think we have enough wheels to manage this). I'm
> open to anywhere personally.

I have some responsibilities that wrap up around 6, so I could probably skip
the MAGIC Center prelims but find folks at the food venue soon afterwards.
 
> Attendees
> 
> Currently, the people I have confirmed for this are:
> 
>   • @Serubin
>   • @Nolski
>   • @brendan-w
>   • @wilfriedE
>   • @repkam09
>   • @Awmusic12635
>   • @sacratoy (not fully confirmed yet)
>   • @abkahrs (not fully confirmed yet)
> 
> Of course, this invite is open to any members of FOSS@RIT too. Not sure if
> @schneidy or @ritjoe would be interested, but the invite definitely extends to
> them too. 😄 If you see this issue and you're interested in hanging with us on
> Tuesday, drop a line here so we know to expect you.
> 
> If I forgot anything or anyone, hopefully someone can fill the gaps.

@itprofjacobs is back in the US any time now, I think. Beyond that, I can't
say, but maybe with this mention we can pull him in. 

Maybe @threebean or @qalthos can make it and, if not, at least help round
out the mentions for other RIT FOSS alumni who are based in or otherwise
often in the area?

-- 
Joe

**Comment by itprofjacobs** [comment]
I have to drive my daughter to MA and back on Tuesday.  Doubtful I'll make it but possible. Weds would let folks do FOSS hours and then go out but whatever works

**Comment by ritjoe** [comment]
On Sun, Aug 21, 2016 at 02:32:02PM -0700, Joe wrote:
> On Sat, Aug 20, 2016 at 10:38:31PM -0700, Justin W. Flory wrote:
> > What is it?
> >
> > As discussed earlier in IRC and/or other communication channels, there's a
> lot
> > of people in the Rochester area for the next few days who will not be here
> for
> > much longer, whether it's for co-op, careers, or other reasons. To take
> > advantage of this convenient timing, we'd like to get some of the FOSS@RIT
> > folks together for a small get-together and probably dinner too.
[...]
> Maybe [redacted] ... can make it ...

oops, that's what I get for doing the mention off the top of my head.

I meant to mention @ralphbean whose other moniker was apparently already
taken when it came time to get a github account.  I knew this at one
point, but had forgotten. :(

Sorry.

-- 
Joe

**Comment by jflory7** [comment]
@schneidy Ah, okay, we'll have to get you later then. Maybe @Nolski and @brendan-w would also be down to hop in on Wednesday (I know @Serubin is leaving sometime on Wednesday). Unfortunately, I won't be in FOSShours this semester from 5pm to 6pm (have a class starting right then).

Pinging @ryansb here too since he was pinged in-channel. And of course, if @ralphbean and @Qalthos are in town and wanting some to grab some food, they're more than welcome!

**Comment by ralphbean** [comment]
Doh!  I'm out of town on Tuesday.  Will be back on Wednesday, though.  ;)

**Comment by Awmusic12635** [comment]
Though I am not sure it will run the whole time period, considering it is the first class, I technically have class until 6:15 on tuesday

**Comment by jflory7** [comment]
I was hoping to get a chance to talk to some people about it, but it seems like that might be hard to day. I was thinking we could maybe go to [Peppermints](http://www.peppermintsrestaurant.com/) diner, where me, @brendan-w, @Nolski, and a few others have been before. Not sure, I'm really open to anywhere, but thought I would throw this out.

# Plan for now

As of now, the current plan is…

* **Where**: MAGIC Center, by comfy chairs
* **When**: Tuesday, Aug. 23, 2016, ~6:00pm US EST

And probably leaving for food around 6:30pm (I know @Awmusic12635 will be coming from a 6:15pm class on Tuesday, for example).

**Comment by Nolski** [comment]
Will follow up on this in the morning but the tentative plan looks good to me. :shipit:

**Comment by ryansb** [comment]
Peppermint's is pretty great - and I believe they serve all-day breakfast. I'll try to meet y'all at the MAGIC center, but if traffic coming from Buffalo sucks, I'll just go straight to the diner.

**Comment by jflory7** [comment]
If you're around, head on over, we're accumulating now!

**Comment by jflory7** [comment]
Issue resolved, task complete! Thanks everyone that came out tonight, and for everyone that missed out tonight, we'll definitely organize some more of these in the near future.

@brendan-w++
@Nolski++
@Serubin++
@ritjoe++
@abkahrs++
@repkam09++
@wilfriedE++
@Awmusic12635++

![FOSS Family, 2016-08-23](https://i.imgur.com/wVk2wq0.jpg)
