### ISSUE TITLE
Streaming Election Night Hackathon 2016

### ISSUE THREAD

**Issue by jflory7** [FOSSRIT/fossbox-tasks#17]
# Summary

It was requested for a stream to be available for the [2016 Election Night Hackathon](https://bit.ly/ElectionHackathon2016) to have a stream option for people to watch remotely.
# Analysis

We briefly discussed this with @schneidy and @jhlachapelle in our hackathon planning meeting today. While this is a stretch goal and not a high priority, it would be helpful if we could have a stream set up if we can get some questions answered and logistics figured out.

Questions we need answered to make this possible:
1. Is this something permissible or without problem by RIT / university policies?
2. What platform are we streaming to? What options are available to us?
3. Are we able to get a laptop dedicated to streaming the entire night?

Once these questions are answered, we should be able to set up the laptop with something like OBS and get to streaming. I also talked with @wilfriedE moments ago, and he was planning on bringing the old decause laptop into FOSSHours for wiping, so we could use this one for that.
# Implementation
1. Double-check for any conflict or issue with streaming this event ourselves.
2. Determine what platform and what account we stream to (Twitch seems viable).
3. Set up a laptop with the appropriate software (OBS seems viable).
4. Test it, set it up during the event, advertise the stream link.

**Comment by ritjoe** [comment]
On Tue, Oct 25, 2016 at 04:50:23PM -0700, Justin W. Flory wrote:
>  What options are available to us?

Just throwing this out there for reference:

https://www.fsf.org/blogs/sysadmin/abyss-the-genesis-of-a-fully-free-streaming-software-package-used-at-libreplanet

-- 
Joe

**Comment by jflory7** [comment]
@ritjoe Unless I'm just not looking closely enough, it doesn't seem ABYSS is ready for final use yet (at least, I don't see it packaged in Fedora). But it seems like an interesting thing to keeps tabs on over the next year.

In the meanwhile, we could use something OBS, which will still keep the FOSSiness there with our streaming.

**Comment by jflory7** [comment]
So we have determined that we will use @wilfriedE's inherited laptop from MAGIC (which he was returning since he has his own now) and set it up with some sort of streaming software in the week leading up to the Election Night Hackathon. More progress on this coming soon… :smile:

**Comment by jflory7** [comment]
We wiped Wilfried's old laptop but having issues getting it to boot. After I get out of my classes today, I'm going to spend some more time trying to provision it and get it ready.

**Comment by jflory7** [comment]
Successfully streamed the event!
