### ISSUE TITLE
Promoting the 2016 Election Night Hackathon

### ISSUE THREAD

**Issue by jflory7** [FOSSRIT/fossbox-tasks#18]
# Summary

The [2016 Election Night Hackathon](https://bit.ly/ElectionHackathon2016) is November 8th, 2016. We need to help promote the event across the RIT community to get people to RSVP to the Eventbrite page for food ordering purposes.
# Analysis

While a simple task in description, it's more challenging than it seems. To help spread the word, we are looking into various ways of spreading word. There are official and unofficial channels we are going through. Those methods are listed below.

We definitely need help from the FOSS@MAGIC community to help spread the word for this, especially in the unofficial methods listed below. Some of these are things anyone with a social media account can help with or just small things you can do to help promote the event. If you want to contribute, drop a comment in the ticket and we can either provide advice or resources to help you promote the event!
### Official
- RIT Message Center email announcement
- MAGIC social media pages (Facebook and Twitter)
- FOSS@RIT mailing list (requires @schneidy)
- Facebook event (hopefully to be created soon by Jen)
### Unofficial
- Hanging posters across campus
- Sharing the [EventBrite page](https://bit.ly/ElectionHackathon2016) on personal social media accounts
- Posting the [poster image](https://cloud.githubusercontent.com/assets/4721034/19708557/67eeb98e-9aed-11e6-8b33-4627d85c3d4a.png) (shown below) in Facebook groups or sending it to friends
- Word of mouth!
# Implementation

If you're a student or someone with time and willing to help, you can do the following things…
1. Share the [MAGIC Facebook post](https://www.facebook.com/ritmagic/photos/a.508150555899544.1073741825.477856358928964/1126336874080906/?type=3)
2. Tell your friends and ask them to come and hang out in the MAGIC Center on Election Night
3. Get posters from @schneidy, @jhlachapelle, or @schneidy and help hang some across campus.
# Poster design

Awesome poster design courtesy of @JacquelineDMcGraw.

![electionnighthackathon](https://cloud.githubusercontent.com/assets/4721034/19708557/67eeb98e-9aed-11e6-8b33-4627d85c3d4a.png)

**Comment by jflory7** [comment]
As a status update, I would say that promotion is going pretty well – we're somewhere over 110 registered attendees so far!

**Comment by schneidy** [comment]
More like 125.

**Comment by jflory7** [comment]
Awesome. :smile: Now our next challenge is logistics for fitting this number of people into one space! However, I would consider this a good problem to have. Interest is high!

**Comment by jflory7** [comment]
I just sent an email out to the [FLOSS Seminar mailing list](https://lists.rit.edu/mailman/listinfo.mmcgi/floss-seminar) with a short reminder about the event. I'm going to close this issue since the event is today – time for promotion is up!
