### ISSUE TITLE
🎉 HFOSS Key Signing Party! 🎉

### ISSUE THREAD

**Issue by Nolski** [FOSSRIT/fossbox-tasks#26]
When do we meet?
==============

- **Date**: Tuesday, November 22nd, 2016
- **Time**: 09:30am - 10:45am

Summary
=======

@ritjoe Is having a key signing party for his class and you are all invited! 

Where?
======

**RIT - ORN 1375**

Who's invited?
===========

- @ritjoe 
- @tcreeds 
- @PatrickGormley 
- @adf5051 
- @decause 
- @nolski
- @jflory7

Feel free to add people who might want to come.

**Comment by jflory7** [comment]
I'll most definitely be there! It would be awesome to have a key-signing party and integrate some more people into the Web of Trust. Before I go tagging people and sending people PMs, I want to double-check with @ritjoe that an open invitation for class next Tuesday is okay? If so, I will definitely extend the invite out and try to promote it as a chance to become integrated into the Web of Trust.

**Comment by ritjoe** [comment]
Sorry, yes, it's good.

The room is Orange Hall 1380

**Comment by ritjoe** [comment]
On Thu, Nov 17, 2016 at 11:28:49AM -0800, Mike Nolan wrote:
> When do we meet?
> 
>   • Date: Tuesday, November 22nd, 2016
>   • Time: 09:30am - 10:45am
> 
> Summary
> 
> @ritjoe Is having a key signing party for his class and you are all invited!
> 
> Where?
> 
> RIT - [ORN 1380]
> 
> Who's invited?
> 
>   • @decause
>   • @nolski
> 
> Feel free to add people who might want to come.

Please send me either the full fingerprint of the public key you'd like
signed, if the key is available from the keyserver network (can be imported
from, for example, pgp.mit.edu). If it isn't on a public keyserver, please
send me an ASCII-armored copy of it (eg, via gpg -a --export) included
inline via email or as an attachment.

Please send your public key or key fingerprint to me by ... 10pm tonight.

It would be OK to send it attached to this thread, I guess, but probably
best if it goes to keysigning2016@etrumeus.com (almost time for a new alias
for that, eh?!).

-- 
Joe

**Comment by jflory7** [comment]
@FOSSRIT/foss-magic-faculty-and-staff @FOSSRIT/friends-of-foss @FOSSRIT/hfoss-2016-fall @FOSSRIT/students-class-of-2017 @FOSSRIT/students-class-of-2018 @FOSSRIT/students-class-of-2019 @FOSSRIT/students-class-of-2020 

Anyone who wants to attend the GPG key signing party tomorrow is welcome to join in! If you're interested in joining us on Tuesday, Nov. 21, 2016 from 9:30am to 10:45am in Orange Hall on RIT's campus, please drop a line in this issue so we know who to expect. All are welcome to join us!

**Comment by jflory7** [comment]
Here is a ZIP containing a text file with my public key. Also forwarding to @ritjoe's email…

[014131E4-public.key.zip](https://github.com/FOSSRIT/fossbox-tasks/files/604317/014131E4-public.key.zip)

**Comment by jflory7** [comment]
Key signing party is getting started soon!

**Comment by jflory7** [comment]
Key signing party success!

![hfoss key signing party 2016](https://cloud.githubusercontent.com/assets/4721034/20529147/342e0698-b09d-11e6-852e-8ed415312f39.jpg)
