### ISSUE TITLE
Planning a final FOSS Family dinner - Sat., 2016 Dec. 10, 6pm

### ISSUE THREAD

**Issue by jflory7** [FOSSRIT/fossbox-tasks#27]
# Summary

As the end of the semester approaches, this will be the last time the FOSS community at RIT will have a chance to meet and it would be nice to organize another dinner like we did in #16.

# What is it?

This isn't a new type of event for us to plan! Like we did in #16 and #20, we'd like to do a dinner together with the FOSS community as we wrap up the end of the semester. Since the end of the semester is a _very_ different time than the beginning of the semester, I hope everyone can try to have some flexibility for an hour or maybe two of their time. We usually meet somewhere on campus, disperse people across cars, and drive over to the restaurant. It's super casual and we'd love to have you come!

# When?

* **Date**: December 10th, 2016
* **Time**: Meet at ~5:30pm, arrive at restaurant at 6pm

# Where?

### Meet at

Between **5:30pm and 5:50pm**, arrive at **MAGIC Center on RIT's campus** (if you have a car and we don't need your help carpooling, you can drive straight there).

### Restaurant

In #16, we went to Peppermint's just a little bit off campus. I'd like to propose we go there again!

* **Name**: Peppermints Restaurant
* **Website**: [peppermintsrestaurant.com](http://www.peppermintsrestaurant.com/)
    * **[Menu](http://www.ipagepro.com/peppermintsrestaurant/logos/menu.pdf)**
* **Address**: 4870 West Henrietta Road, Henrietta, NY 14467

# You're invited!

I'm tagging as many people I can think, but it's not an exhaustive list. If you're not tagged and want to come, please feel free to comment and let us know you'd like to come! If you plan to come, **please leave a comment confirming you will come** so we can plan carpooling as necessary. If you _have_ a car and would be willing to take some passengers, that would be nice to know. 😄 

## Confirmed

* @jflory7 [~~_car_~~]
* @Awmusic12635 [_car_]
* @wilfriedE 
* @ColdSauce 
* @itprofjacobs [_car_]
* @nathaniel486 [_car_]
* @repkam09 [_car_]
* @abkahrs 
* @thenaterhood 
* @Qalthos 
* @xforever1313 [_car_]
* @ritjoe

## Invited

* @atla5 
* @adf5051 
* @brendan-w 
* ~~@Chris-Bitler~~
* ~~@cprofitt~~ 
* ~~@craigcabrey~~
* @decause 
* @msoucy 
* ~~@ryansb~~ 
* ~~@schneidy~~
* ~~@Serubin~~
* @ralphbean 
* @FOSSRIT/friends-of-foss 
* @FOSSRIT/foss-magic-faculty-and-staff 
* @FOSSRIT/friends-of-foss 
* @FOSSRIT/hfoss-2016-fall 
* @FOSSRIT/students-class-of-2016 
* @FOSSRIT/students-class-of-2017 
* @FOSSRIT/students-class-of-2018 
* @FOSSRIT/students-class-of-2019 
* @FOSSRIT/students-class-of-2020

**Comment by Awmusic12635** [comment]
I'm good for the 10th

**Comment by wilfriedE** [comment]
The 10th works for me as well.

**Comment by Chris-Bitler** [comment]
I think I can go

**Comment by jflory7** [comment]
@Chris-Bitler Okay, awesome, I will add you to the confirmed list for now then! 👍

**Comment by ColdSauce** [comment]
I'll come too!!

**Comment by itprofjacobs** [comment]
Can come. Can Drive

**Comment by nathaniel486** [comment]
will be there.  Can drive if needed maybe

**Comment by schneidy** [comment]
Unfortunately, I'm out of town that weekend. Sad to be missing one last big meal with everyone.

**Comment by repkam09** [comment]
I can be there. And I have a car that can carry me + 4 if needed.

**Comment by abkahrs** [comment]
I should be able to make it.

**Comment by thenaterhood** [comment]
I'll try to make it!

**Comment by cprofitt** [comment]
I will be unable to attend. My daughter is performing in a play and my
parents are going to be in town.

Charles

**Comment by Qalthos** [comment]
I should be able to make it

**Comment by ryansb** [comment]
I can't, I've got family in town.

**Comment by ritjoe** [comment]
Just mentioned this to @alexanderkyte this afternoon.

**Comment by ritjoe** [comment]
I've been working with @mstarenko and @jparryhill on some FOSS course stuff and am always trying to rope them into further FOSS immersion. :smile:

What better way to further my nefarious schemes than through an invitation to a dinner that I have not yet completely cleared my schedule for? :wink:

**Comment by Awmusic12635** [comment]
Think we should call ahead so we don't catch them by surprise?

**Comment by ritjoe** [comment]
I see @ad5051 on the invited list, but am going to go ahead and use this comment to invite @PatrickGormley and @tcreeds, to specifically round out this semester's HFOSS contingent.

**Comment by jflory7** [comment]
@Awmusic12635: I called them five minutes after they closed and didn't get an answer. I'll try again tomorrow.

@ritjoe: Ahh, I think I remembered the @FOSSRIT/hfoss-2016-fall tag after adding @adf5051, which is why @PatrickGormley and @tcreeds didn't make it on that list. Not to exclude them from the invitation list. 😏 I do remember tcreeds saying he would not be able to make it.

**Comment by jflory7** [comment]
Just called Peppermints – we're all set for Saturday!

**Comment by thenaterhood** [comment]
:D :D

**Comment by jparryhill** [comment]
Regret to report that I have a prior engagement on Saturday 12/10, and will not be able to attend. Boo!

Wishing you all a smooth end of semester.

**Comment by craigcabrey** [comment]
Unfortunately I'm not going to be back in NY anytime soon, otherwise I would've loved to join.

**Comment by Chris-Bitler** [comment]
I'm no longer able to make it. I need to buckle down for finals, and so I can't make this. Sorry :/

**Comment by mstarenko** [comment]
Alas, I'm out of town tomorrow night and will be unable to attend your dinner--but thank you for the invite. I look forward to meeting you all at some future occasion. To the end of the semester: Cheers!

**Comment by thenaterhood** [comment]
@xforever1313?

**Comment by xforever1313** [comment]
@thenaterhood: if it's not too late to confirm,  I can go.   I also have a car that can fit 2 more people.

**Comment by jflory7** [comment]
@Awmusic12635 @wilfriedE @ColdSauce @itprofjacobs @nathaniel486 @repkam09 @abkahrs @thenaterhood @Qalthos @xforever1313 @atla5 @adf5051 @PatrickGormley @decause
@ritjoe Reminder that tonight is FOSS Family dinner! Right now, the plan is for us to initially meet in the MAGIC Center around 5:30pm and arrive at the restaurant at 6:00pm.

@Awmusic12635 @nathaniel486 @repkam09 @xforever1313 Think we could recruit the four of you for carpooling? Turns out I'm decommissioned from a car for a bit longer, so I won't be able to help carpool. I think the four of you should allow us to fit everyone together.

Everyone else, you can meet us at MAGIC at 5:30pm or at the restaurant at 6:00pm. Looking forward to seeing you all tonight!

**Comment by Awmusic12635** [comment]
Yes I can

**Comment by nathaniel486** [comment]
sure thing

**Comment by xforever1313** [comment]
Can do.

**Comment by ritjoe** [comment]
On my way.

**Comment by jflory7** [comment]
#IssueClosed Another successful FOSS Family dinner. 😄 Thanks everyone for coming out tonight, and good luck with finals and/or enjoy the holidays! We'll see most of you in 2017.

Next semester, @Serubin will need to carry the torch for the FOSS Family dinners. 😉 

![group photo](https://cloud.githubusercontent.com/assets/4721034/21077186/1ec74dfa-bf11-11e6-9c5a-b271fc3e5228.jpg)
![alex and wilfried](https://cloud.githubusercontent.com/assets/4721034/21077187/20cb7c2a-bf11-11e6-8857-ac5a4815416c.jpg)
![end of the table](https://cloud.githubusercontent.com/assets/4721034/21077189/22c60018-bf11-11e6-9a5d-b0aef64ad164.jpg)
![wilfried d joe sj and alex](https://cloud.githubusercontent.com/assets/4721034/21077190/248835ce-bf11-11e6-951c-437db46a2377.jpg)
