### ISSUE TITLE
Winter Break FOSS Meetup - Tuesday, Dec. 20th, 2pm

### ISSUE THREAD

**Issue by Nolski** [FOSSRIT/fossbox-tasks#28]
# When?

Tuesday 12/20? Or whenever.

**Edit, 12/19**: Let's do Tuesday, December 20th, 2016 at 2pm!

# Where?

Well it depends on the time. We could hit up a diner or some restaurant for some brunch. Or just get coffee at [fuego](http://www.fuegocoffee.com/) or [joe bean](www.joebeanroasters.com/), or we could do a dinner and drinks ordeal at [victoirs](www.victoirebar.com/) which has some tasty food and good beer for those who are of age or have proper identification

**Edit, 12/19**: Fuego's seems to be like the best choice? Address is:

**[Fuego Coffee](http://www.fuegocoffee.com/)**
45 Euclid Street
Rochester, NY 14604
_[Google Maps](https://goo.gl/maps/VXviEP1hGPD2)_

# Who?

## Confirmed

* @Nolski 
* @jflory7
* @thequbit 
* @decause (tentative)
* @schneidy (tentative)

## Invited

* ~~@itprofjacobs~~
* @brendan-w 
* @cprofitt 
* ~~@thenaterhood~~

And others whom I've probably forgotten!

**Comment by itprofjacobs** [comment]
Not back in town til the 22nd

Can leave campus at noon on the 22nd.

On the 23rd free except 10:30-11:00 meeting in Brighton

**Comment by jflory7** [comment]
I am definitely down. My travel plans keep changing, so now it looks like I'll be taking a rental car home. I would prefer earlier in Tuesday (maybe like 2pm-4pm), but I should be flexible in the evening if need be.

@Nolski My suggestions if we do food earlier in the day is the [Arnett Cafe](http://thearnettcafe.com/). Otherwise, Fuego's is always a good choice (and it would give me an excuse to get good coffee one last time in Rochester). Also, do you have transportation around ROC squared away yet?

I did check in with @schneidy today, and he said that later on Tuesday (I think it was after 2pm) should be good for him.

**Comment by thequbit** [comment]
I'm down.  During the day ( so lunch/coffee/etc. ) would be best for me.

**Comment by jflory7** [comment]
# Confirming a time

Okay, we're a day out! I went ahead and locked down Tuesday, December 20th, 2016, 2:00pm at Fuego's as the meetup date and location. Hopefully this will work for as many people as possible.

# Transportation?

There is a chance I'll have my rental vehicle squared away by tomorrow, but even if it is, I'm reluctant to put any more miles than I have to in this weather (plus, it will be filled with most of my boxes / belongings). Would anyone be able to offer a ride to pick me up from RIT and bring me to Fuego's tomorrow? Not sure who we have confirmed to come yet, but I pinged a few people to see what their availability was like.

# CC

* @decause 
* @schneidy 
* @brendan-w 
* @cprofitt 
* @thenaterhood 
* @ritjoe

**Comment by jflory7** [comment]
My roommate and his friend would be interested in coming, so hopefully room to grab me and two others too would be helpful.

@Nolski, did you get your transportation settled yet or are you still figuring that out?

**Comment by Nolski** [comment]
I have a car. If need be I can pick people up but I'm all the way up in Webster so driving down to Henrietta might be a bit of a pain.

**Comment by jflory7** [comment]
@Nolski Change of plans for me. I have a rental and I'll need to take it out to get gas too, so I should be able to drive to Fuego's.

**Comment by ritjoe** [comment]
It happened. It was good.
