### ISSUE TITLE
Schedule FOSSBox Grad Party

### ISSUE THREAD

**Issue by mansam** [FOSSRIT/fossbox-tasks#3]
We would like to try and schedule a FOSSBox grad party, tentatively at 4:00pm on Saturday, May 24.

Things to do
* Reserving the room
* Figuring out food
* Invite the people (Parents,HFOSS,advFOSS, etc..)

#info on graduation: http://www.rit.edu/~w-comenc/ceremonies.php

**Comment by jflory7** [comment]
Even though this issue is two years old, it might be interesting to do this for this year's class. I know this year the OSCON trip is during finals week, so that might be a conflict of interest. @Nolski, what do you think?

**Comment by Nolski** [comment]
@jflory7 I think there is something planned for Friday after commencement or something?

**Comment by msoucy** [comment]
I hope so!

**Comment by jflory7** [comment]
@Nolski @msoucy I think we mentioned this in FOSShours last week, but I forgot what the discussion was. I just emailed @itprofjacobs and @schneidy about it to see if there was already something officially on the books.

**Comment by jflory7** [comment]
Latest from SJ:
> So it's basically got to be before 11:00 or after 9:30 I don't recall there being a lot of takers.  I think Brendan isn't going to graduation.

Not sure anything is on the books right now.

**Comment by Nolski** [comment]
🎉
