### ISSUE TITLE
Sync FOSSRIT forks of student projects?

### ISSUE THREAD

**Issue by axk4545** [FOSSRIT/fossbox-tasks#31]
@ritjoe @jflory7 Not sure if this is something that needs to be done or not. I am currently going through and submitting PRs to do this.
below are the repos that are out of sync:
https://github.com/FOSSRIT/python-OBD
https://github.com/FOSSRIT/hfoss
https://github.com/FOSSRIT/PaintPartners
https://github.com/FOSSRIT/gitsniffer
https://github.com/FOSSRIT/monroe-elections
https://github.com/FOSSRIT/Dash
https://github.com/FOSSRIT/PyTalk
https://github.com/FOSSRIT/sensenet
https://github.com/FOSSRIT/monroe-elections-data
https://github.com/FOSSRIT/Piglet
https://github.com/FOSSRIT/NeuroPi
https://github.com/FOSSRIT/10ftwm
https://github.com/FOSSRIT/vAnalyze.js
https://github.com/FOSSRIT/atom-dlang
https://github.com/FOSSRIT/validator.py
https://github.com/FOSSRIT/Flask-Analytics
https://github.com/FOSSRIT/badges
https://github.com/FOSSRIT/URIx-Util
https://github.com/FOSSRIT/arduino_ir
https://github.com/FOSSRIT/FOSSTimeline
https://github.com/FOSSRIT/nunjucks-brunch
https://github.com/FOSSRIT/Boy_meets_girl
https://github.com/FOSSRIT/monroeminutes
https://github.com/FOSSRIT/uspto-scrape
https://github.com/FOSSRIT/pypi2fedora
https://github.com/FOSSRIT/Fedora-Badges-Ideas
https://github.com/FOSSRIT/POSSE-RIT-2012

**Comment by abkahrs** [comment]
Most of the forks that are only behind master in commits just need to be merged. @FOSSRIT/foss-magic-faculty-and-staff

**Comment by jflory7** [comment]
I think it's a good thing to keep updated and I have no qualms with it. I think I will be able to merge them all in, I think?

P.S. – A script for this that would do it all automatically could be really cool, not sure how it would work, but it would be nice.

**Comment by abkahrs** [comment]
@jflory7 below repos are both behind and ahead in commits
https://github.com/FOSSRIT/hfoss
https://github.com/FOSSRIT/PaintPartners
https://github.com/FOSSRIT/monroe-elections
https://github.com/FOSSRIT/monroe-elections-data
https://github.com/FOSSRIT/badges
https://github.com/FOSSRIT/FOSSTimeline
https://github.com/FOSSRIT/uspto-scrape
https://github.com/FOSSRIT/POSSE-RIT-2012

**Comment by Chris-Bitler** [comment]
@jflory7 The main issue with using a script for this is that you would still have to manually deal with any merge conflicts.

**Comment by jflory7** [comment]
@abkahrs Are there any more pending repositories to update? If not, are we good to close this issue? 🎬

**Comment by jflory7** [comment]
I followed up with @axk4545 in IRC and he confirmed that this is good to close. 🎬
