### ISSUE TITLE
Moz Campus Club teams seek campus FOSS participants for remote info interviews

### ISSUE THREAD

**Issue by ritjoe** [FOSSRIT/fossbox-tasks#32]
From:

https://www.reddit.com/r/rit/comments/5qke82/mozilla_is_recruiting_students_for_a_study_on/

_The Mozilla Campus Clubs team (https://campus.mozilla.community/) is recruiting students who are interested in participating in, or are already active in, on-campus Open Source development communities for a study. We want to learn what types of projects motivate you, and what Mozilla can do to help support those projects._

_We are conducting a series of 1 hour interview sessions. The interviews will take place remotely via Google Hangouts or another video conference platform. Interviewees will be compensated for their participation._

Contact info at the indicated page. hat tip to @Awmusic12635

**Comment by jflory7** [comment]
I went ahead and sent a quick note [on the fossrit@lists.fedorahosted.org mailing list](https://lists.fedoraproject.org/archives/list/fossrit@lists.fedorahosted.org/thread/DYL7NKFWHHBZ4PX737KZ2H3H4DOESCQ5/) about this topic to help raise awareness while the window is still open. Unless @schneidy wants to send something on the larger announcement list, I'm going to close this issue as being completed. @ritjoe++ @Awmusic12635++

**Comment by schneidy** [comment]
I was going to send it out with the announcement about the upcoming Net
Neutrality Round Table.

**Comment by jflory7** [comment]
@schneidy Okay, cool – still probably not a bad idea to do it there because that list has a much larger number of people subscribed to it!
