### ISSUE TITLE
Planning the spring 2017 FOSS Family dinner - Wednesday, May 17, 2017

### ISSUE THREAD

**Issue by jflory7** [FOSSRIT/fossbox-tasks#42]
# Summary

It's that time again… May isn't far off and soon it will be the last time the FOSS community at RIT will have a chance to meet for a final dinner before departing for the summer.

# What is it?

This isn't a new type of event for us to plan! Like we did in #16, #20, #27, and #28, we'd like to do a dinner together with the FOSS community as we wrap up the end of the semester. The end of the semester is trickier to coordinate because of exams and especially travel plans this semester. Hopefully everyone can try to have some flexibility for an hour or maybe two of their time. We usually meet somewhere on campus, disperse people across cars, and drive over to the restaurant. It's super casual and we'd love to have you come!

# When?

* **Date**: Wednesday, May 17, 2017
* **Time**: Carpool meets at 6:30pm [???]
    * _In the past, we've met around 5:30pm to arrive at the restaurant near 6pm._

# Where?

### Meet at…

TBD!

### Restaurant

In #16 and #27, we went to Peppermint's just a little bit off campus. To make life easy, everyone could go there again to continue the tradition (and milkshakes).

* **Name**: Peppermints Restaurant
* **Website**: [peppermintsrestaurant.com](http://www.peppermintsrestaurant.com/)
    * **[Menu](http://www.ipagepro.com/peppermintsrestaurant/logos/menu.pdf)**
* **Address**: 4870 West Henrietta Road, Henrietta, NY 14467

# You're invited!

I'm tagging the usual suspects, but it's not an exhaustive or comprehensive list. (I'm also not on campus to help poke people about this, so any help on this would be appreciated!) If you're not tagged and want to come, please feel free to comment and let us know you'd like to come! If you plan to come, **please leave a comment confirming you will come** so we can plan carpooling as necessary. If you _have_ a car and would be willing to take some passengers, that would be nice to know. 😄 

## Confirmed

* @Awmusic12635 
* @axk4545 
* @bxs9775 
* @cprofitt 
* @itprofjacobs [car]
* @nathaniel486 [car]
* @repkam09 
* @ritjoe 
* @schneidy 
* @Serubin [car]
* @thenaterhood 
* @xforever1313 [car]

## Invited

* @atla5 
* @brendan-w 
* @Chris-Bitler
* @ColdSauce 
* @craigcabrey
* @decause 
* @itprofjacobs 
* ~~@jflory7~~
* @msoucy 
* @Qalthos 
* @ryansb
* @ralphbean 
* @wilfriedE 
* @FOSSRIT/friends-of-foss 
* @FOSSRIT/foss-magic-faculty-and-staff 
* @FOSSRIT/friends-of-foss 
* @FOSSRIT/hfoss-semester-2161 
* @FOSSRIT/hfoss-semester-2165 
* @FOSSRIT/students-class-of-2016 
* @FOSSRIT/students-class-of-2017 
* @FOSSRIT/students-class-of-2018 
* @FOSSRIT/students-class-of-2019 
* @FOSSRIT/students-class-of-2020 

(I might be 4500 miles away but you can sure bet I'm going to make sure there's a FOSS Family dinner. 😉)

**Comment by cprofitt** [comment]
I will try to make it this year. Peppermints sounds good to me.

**Comment by ritjoe** [comment]
On Sun, Apr 09, 2017 at 01:52:48PM -0700, cprofitt wrote:
> I will try to make it this year. Peppermints sounds good to me.

:+1:

In the absence so far of very much in terms of day-of-week or other
date-related restrictions, you got any constraints we can begin to shape
things up around?

(I need to look at my own household calendar, to be honest, but it's a
start.) 
 
> On Sun, 2017-04-09 at 09:53 -0700, Justin W. Flory wrote:
[...]
> > When?
> > Date: TBD
> > Time: TBD
> > In the past, we've met around 5:30pm to arrive at the restaurant near
> > 6pm.
> > Where?
> > Meet at…
> > TBD!
> > Restaurant
> > In #16 and #27, we went to Peppermint's just a little bit off campus.
> > To make life easy, everyone could go there again to continue the
> > tradition (and milkshakes).
> > Name: Peppermints Restaurant
> > Website: peppermintsrestaurant.com
> > Menu
> > Address: 4870 West Henrietta Road, Henrietta, NY 14467
[...]

**Comment by Awmusic12635** [comment]
As long as its not a thursday I should be pretty flexible

**Comment by repkam09** [comment]
I can be available just about any day in the evening. 👍

**Comment by axk4545** [comment]
Will need some notice of when and transportation to wherever it is. Friday's are generally good for me.

**Comment by nathaniel486** [comment]
It should probably be after Imgaine, but before finals week.  I'm free most
nights so any day would probably work for me.

**Comment by schneidy** [comment]
SJ and I will be gone the week before Imagine RIT due to RedHat Summit, and the week after Imagine RIT due to OS Con. We tossed around the idea of meeting during FOSS Hours during finals week.

**Comment by ritjoe** [comment]
Looking back at the now-closed #29

https://github.com/FOSSRIT/fossbox-tasks/issues/29

for the reference of those of us not full time at RIT, 

Imagine RIT is Sat May 6 and 

Finals are May 15-19.

That would then put an instead-of-FOSS-hours dinner on Wednesday, May 17.

-- 
Joe

**Comment by itprofjacobs** [comment]
Should we do an eventbrite or is there another way you wanna handle signups?

**Comment by ritjoe** [comment]
RSVP to this thread is how we've done it, and works for me.

**Comment by xforever1313** [comment]
@thenaterhood and I will probably be good to go... depending on when it is :P

I can drive 2 additional people if needed.

**Comment by ColdSauce** [comment]
I will probably be able to make it depending on when it is. I have a class until 8pm on Tuesdays and Thursdays but am free every other evening.

**Comment by jflory7** [comment]
## Proposed: Wednesday, May 17, 2017: 5:30pm meet-time?

Seems like this is the most optimal option?

**Comment by Serubin** [comment]
@jflory7 Sounds good.

I can drive 4 people

**Comment by ritjoe** [comment]
OK, from offline in-person discussions and from past discussion here, we're
firming up on this being two weeks from tonight, eg:

What: FOSS Family Dinner
When: Wednesday, May 17, 2017
Where: Peppermints Restaurant
Who: all welcome
Time: TBD but early evening probably

https://rocwiki.org/Peppermints_Restaurant

http://www.openstreetmap.org/way/263225736#map=18/43.05489/-77.65474

no RSVP strictly required, but responses will ease figuring out seating and
transport.

**Comment by itprofjacobs** [comment]
I'm in.  Can drive three others if needed

**Comment by bxs9775** [comment]
I would like to come. Prof. Jacobs, you said you had room for three others in your car, would you mind if I rode with you?

**Comment by itprofjacobs** [comment]
Should be fine.  I'll be meeting with my class in 2500 at 4:00-5:00

**Comment by Serubin** [comment]
I've also got space in my car.

I think we should aim for 6:30.

**Comment by jflory7** [comment]
Okay, the original comment and issue title are updated with the correct date now.

I see @Awmusic12635 @cprofitt @itprofjacobs @repkam09 @ritjoe @schneidy @bxs9775 @Serubin as confirmed.

@axk4545 @nathaniel486 @xforever1313 @thenaterhood @ColdSauce Does this day / sometime after 5:30pm still work for all of you?

**Comment by nathaniel486** [comment]
Works for me

**Comment by xforever1313** [comment]
Me and @thenaterhood are in!  I can fit two additional people in my car if needed.

**Comment by axk4545** [comment]
works for me but will need to work out a ride

**Comment by Chris-Bitler** [comment]
I want to go to this, but two things:

1. If the carpool leaves before 6 pm, I can't make it, as that is when I get back to campus from work
2. I'm going to need a ride with someone.

Thanks :)

**Comment by schneidy** [comment]
6:30 works for me!

**Comment by bxs9775** [comment]
@itprofjacobs, thank you for the ride. When/where will we be leaving for the restaurant?

**Comment by itprofjacobs** [comment]
My office 70-2671 6:10

**Comment by bxs9775** [comment]
Ok. Thank you.

**Comment by ritjoe** [comment]
OK, everybody, tonight's the night! 

What: FOSS Family Dinner 
When: TONIGHT Wednesday, May 17, 2017 
Where: Peppermints Restaurant 
Who: all welcome 
Time: 6:30 pm 

https://rocwiki.org/Peppermints_Restaurant 

http://www.openstreetmap.org/way/263225736#map=18/43.05489/-77.65474 

no RSVP strictly required, but responses will ease figuring out seating and transport.

If you haven't chimed in yet to let us know you're coming, or if your plans have changed, please let us know in the next couple of hours so we can try to plan seating.

**Comment by schneidy** [comment]
I think you mean tomorrow (Wednesday) is the night.

-Dan

**Comment by Serubin** [comment]
Quick update - I will not have a car available as it will be packed with
things.

**Comment by ritjoe** [comment]
My mind is a time traveller, already in tomorrow.

Unfortunately, I can't see what's happening there very clearly yet, so no
requests for stock tips or racing results, please. 

But yes, tomorrow, if tomorrow is Wednesday.

Thanks, Dan.

**Comment by axk4545** [comment]
@itprofjacobs Still have room in your car? I was going to go with @Serubin but his car will be full.

**Comment by ColdSauce** [comment]
Hey could I get a ride from someone?

**Comment by Awmusic12635** [comment]
I have room in my car as well.

**Comment by axk4545** [comment]
@Awmusic12635 then you win. Can I come with you?

**Comment by Awmusic12635** [comment]
Yes

-- 
Alex Wacker


On May 16, 2017 at 5:28:07 PM, Aidan Kahrs (notifications@github.com) wrote:

@Awmusic12635 <https://github.com/awmusic12635> then you win. Can I come
with you?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FOSSRIT/fossbox-tasks/issues/42#issuecomment-301921017>,
or mute the thread

**Comment by cprofitt** [comment]
I should be attending tomorrow. Hope to see you all there.

CP

**Comment by itprofjacobs** [comment]
I think I've got two seats

**Comment by axk4545** [comment]
@itprofjacobs @Awmusic12635 got me :P

**Comment by ralphbean** [comment]
Sorry all.  I thought I could come tonight but something has come up.  Enjoy Peppermints!

**Comment by ColdSauce** [comment]
@itprofjacobs could I get a ride from you then? where shall we meet?

**Comment by itprofjacobs** [comment]
Anyone who’s getting a ride from me we can meet at my office 70-2671 at 5:30 and we’ll head over.

SJ

**Comment by ColdSauce** [comment]
:+1:

**Comment by bxs9775** [comment]
Ok, thank you for the reminder.

**Comment by itprofjacobs** [comment]
Oops, make that meet at 6:00 in my office for 6:30 arrival :-)

**Comment by bxs9775** [comment]
Got it. See you at 6.

**Comment by Serubin** [comment]
It was yummy! Until next time guys.

**Comment by jflory7** [comment]
@Serubin Pics or it didn't happen! 😉
